# permissions for end users to view resourcequotaautoscalings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourcequotaautoscaling-viewer-role
rules:
- apiGroups:
  - demo.devops.io.my.demo
  resources:
  - resourcequotaautoscalings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.devops.io.my.demo
  resources:
  - resourcequotaautoscalings/status
  verbs:
  - get
