
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - demo.devops.io.my.demo
  resources:
  - resourcequotaautoscalings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.devops.io.my.demo
  resources:
  - resourcequotaautoscalings/finalizers
  verbs:
  - update
- apiGroups:
  - demo.devops.io.my.demo
  resources:
  - resourcequotaautoscalings/status
  verbs:
  - get
  - patch
  - update
